[package]
name = "omnibuild"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ob"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.93"
clap = {version = "4.5.21", features = ["derive"]}
mlua = {version = "0.10.1", features = ["lua54"]}
